import { fft2dInPlace } from '@/lib/fft.js'
import { hexToPixel } from '@/composables/useHexGeometry.js'

// a flat-top hex grid's centers form a lattice generated by a1 = (0, H) and
// a2 = (0.75W, 0.5H), matching hexToPixel. the autocorrelation of the drawn
// grid peaks at every lattice vector: the near-vertical pair gives H, the
// diagonal pairs give W. honeycomb vertex-offset false peaks sit at 0/60/120
// degrees, which is why the angle gates below are +-20 and no wider.
const MIN_WINDOW = 128
const MAX_WINDOW = 1024
const PEAK_RMIN = 6
const ANGLE_TOL = 20
const DIAG_Y_TOL = 0.15
const PHASE_MIN_CONTRAST = 1.5

export function toGrayscale(rgba, width, height) {
  const gray = new Float32Array(width * height)
  for (let i = 0; i < gray.length; i++) {
    const o = i * 4
    gray[i] = 0.299 * rgba[o] + 0.587 * rgba[o + 1] + 0.114 * rgba[o + 2]
  }
  return gray
}

export function gradientMagnitude(gray, width, height) {
  const g = new Float32Array(width * height)
  for (let y = 1; y < height - 1; y++) {
    for (let x = 1; x < width - 1; x++) {
      const i = y * width + x
      const dx = gray[i + 1] - gray[i - 1]
      const dy = gray[i + width] - gray[i - width]
      g[i] = Math.sqrt(dx * dx + dy * dy)
    }
  }
  return g
}

// the gradient of a stroked line is a twin ridge with a dip at the line
// center; a box blur merges the ridges so the phase score peaks on the line
// itself instead of one pixel to either side
export function boxBlur3(field, width, height) {
  const tmp = new Float32Array(width * height)
  const out = new Float32Array(width * height)
  for (let y = 0; y < height; y++) {
    for (let x = 1; x < width - 1; x++) {
      const i = y * width + x
      tmp[i] = (field[i - 1] + field[i] + field[i + 1]) / 3
    }
  }
  for (let y = 1; y < height - 1; y++) {
    for (let x = 0; x < width; x++) {
      const i = y * width + x
      out[i] = (tmp[i - width] + tmp[i] + tmp[i + width]) / 3
    }
  }
  return out
}

export function autocorrelate(field, width, height) {
  let n = 1
  while (n * 2 <= Math.min(width, height, MAX_WINDOW)) n *= 2
  if (n < MIN_WINDOW) return null
  const x0 = (width - n) >> 1
  const y0 = (height - n) >> 1
  let mean = 0
  for (let y = 0; y < n; y++) {
    for (let x = 0; x < n; x++) mean += field[(y0 + y) * width + x0 + x]
  }
  mean /= n * n
  const win = new Float64Array(n)
  for (let i = 0; i < n; i++) win[i] = 0.5 * (1 - Math.cos((2 * Math.PI * i) / (n - 1)))
  const re = new Float64Array(n * n)
  const im = new Float64Array(n * n)
  for (let y = 0; y < n; y++) {
    for (let x = 0; x < n; x++) {
      re[y * n + x] = (field[(y0 + y) * width + x0 + x] - mean) * win[x] * win[y]
    }
  }
  fft2dInPlace(re, im, n)
  for (let i = 0; i < re.length; i++) {
    re[i] = re[i] * re[i] + im[i] * im[i]
    im[i] = 0
  }
  fft2dInPlace(re, im, n, true)
  return { ac: re, n }
}

function clamp(v, lo, hi) {
  return Math.min(hi, Math.max(lo, v))
}

function subpixelPeak(at, dx, dy) {
  const c = at(dx, dy)
  const xm = at(dx - 1, dy)
  const xp = at(dx + 1, dy)
  const ym = at(dx, dy - 1)
  const yp = at(dx, dy + 1)
  const denX = xm - 2 * c + xp
  const denY = ym - 2 * c + yp
  const ox = denX < 0 ? clamp((0.5 * (xm - xp)) / denX, -1, 1) : 0
  const oy = denY < 0 ? clamp((0.5 * (ym - yp)) / denY, -1, 1) : 0
  return { x: dx + ox, y: dy + oy }
}

function localMaxNear(at, cx, cy, rad) {
  const x0 = Math.round(cx)
  const y0 = Math.round(cy)
  let best = null
  for (let dy = -rad; dy <= rad; dy++) {
    for (let dx = -rad; dx <= rad; dx++) {
      const v = at(x0 + dx, y0 + dy)
      if (!best || v > best.v) best = { dx: x0 + dx, dy: y0 + dy, v }
    }
  }
  if (!best) return null
  for (let dy = -1; dy <= 1; dy++) {
    for (let dx = -1; dx <= 1; dx++) {
      if (dx === 0 && dy === 0) continue
      if (at(best.dx + dx, best.dy + dy) > best.v) return null
    }
  }
  return best
}

function refineByHarmonic(at, vec, n, floor) {
  const len = Math.hypot(vec.x, vec.y)
  if (len === 0) return vec
  const kMax = Math.floor((n / 2 - 3) / len)
  for (let k = kMax; k >= 2; k--) {
    const m = localMaxNear(at, vec.x * k, vec.y * k, 3)
    if (m && m.v >= Math.max(floor, 0.1 * vec.v)) {
      const p = subpixelPeak(at, m.dx, m.dy)
      return { x: p.x / k, y: p.y / k, v: vec.v }
    }
  }
  return vec
}

function angleDeg(dx, dy) {
  return (Math.atan2(dy, dx) * 180) / Math.PI
}

function pickShortest(candidates, valueFloor) {
  let best = null
  for (const p of candidates) {
    if (p.v < valueFloor) continue
    const r = p.dx * p.dx + p.dy * p.dy
    if (!best || r < best.r) best = { ...p, r }
  }
  return best
}

export function detectLattice(ac, n) {
  const half = n / 2
  const norm = ac[0]
  if (!(norm > 0)) return null
  const at = (dx, dy) => ac[((((dy % n) + n) % n) * n + (((dx % n) + n) % n))] / norm
  const rMin2 = PEAK_RMIN * PEAK_RMIN
  const rMax = half - 3
  const rMax2 = rMax * rMax
  let sum = 0
  let sumSq = 0
  let count = 0
  for (let dy = -half + 2; dy <= half - 2; dy++) {
    for (let dx = -half + 2; dx <= half - 2; dx++) {
      const r2 = dx * dx + dy * dy
      if (r2 < rMin2 || r2 > rMax2) continue
      const v = at(dx, dy)
      sum += v
      sumSq += v * v
      count++
    }
  }
  if (!count) return null
  const mean = sum / count
  const std = Math.sqrt(Math.max(0, sumSq / count - mean * mean))
  const floor = mean + 3 * std

  const verticals = []
  const diagonals = []
  for (let dy = 0; dy <= half - 2; dy++) {
    for (let dx = -half + 2; dx <= half - 2; dx++) {
      if (dy === 0 && dx <= 0) continue
      const r2 = dx * dx + dy * dy
      if (r2 < rMin2 || r2 > rMax2) continue
      const v = at(dx, dy)
      if (v <= floor) continue
      if (
        at(dx - 1, dy) >= v || at(dx + 1, dy) >= v ||
        at(dx, dy - 1) >= v || at(dx, dy + 1) >= v ||
        at(dx - 1, dy - 1) >= v || at(dx + 1, dy - 1) >= v ||
        at(dx - 1, dy + 1) >= v || at(dx + 1, dy + 1) >= v
      ) continue
      const a = angleDeg(dx, dy)
      if (Math.abs(a - 90) <= ANGLE_TOL) verticals.push({ dx, dy, v })
      else if (Math.abs(a - 30) <= ANGLE_TOL || Math.abs(a - 150) <= ANGLE_TOL) diagonals.push({ dx, dy, v })
    }
  }
  if (!verticals.length || !diagonals.length) return null

  let vMax = 0
  for (const p of verticals) vMax = Math.max(vMax, p.v)
  let dMax = 0
  for (const p of diagonals) dMax = Math.max(dMax, p.v)
  const u0 = pickShortest(verticals, 0.5 * vMax)
  const d0 = pickShortest(diagonals, 0.5 * dMax)
  if (!u0 || !d0) return null

  const lenRatio = Math.hypot(d0.dx, d0.dy) / Math.hypot(u0.dx, u0.dy)
  if (lenRatio < 0.6 || lenRatio > 1.6) return null

  const third = localMaxNear(at, u0.dx - d0.dx, u0.dy - d0.dy, 2)
  if (!third || third.v < Math.max(floor, 0.25 * Math.min(u0.v, d0.v))) return null

  let u = { ...subpixelPeak(at, u0.dx, u0.dy), v: u0.v }
  let d = { ...subpixelPeak(at, d0.dx, d0.dy), v: d0.v }
  u = refineByHarmonic(at, u, n, floor)
  d = refineByHarmonic(at, d, n, floor)

  const theta = Math.atan2(-u.x, u.y)
  const hexHeight = Math.hypot(u.x, u.y)
  const cos = Math.cos(theta)
  const sin = Math.sin(theta)
  const dx0 = d.x * cos + d.y * sin
  const dy0 = -d.x * sin + d.y * cos
  if (Math.abs(dy0 - hexHeight / 2) > DIAG_Y_TOL * hexHeight) return null
  const hexWidth = Math.abs(dx0) / 0.75
  if (!(hexWidth > 0)) return null
  const ratio = hexHeight / hexWidth
  if (ratio < 0.55 || ratio > 1.2) return null

  return {
    hexWidth,
    hexHeight,
    rotation: (theta * 180) / Math.PI,
    strength: Math.min(u.v, d.v),
  }
}

export function latticeFromParams({ hexWidth, hexHeight, rotation }) {
  const rad = (rotation * Math.PI) / 180
  const cos = Math.cos(rad)
  const sin = Math.sin(rad)
  const rot = (x, y) => ({ x: x * cos - y * sin, y: x * sin + y * cos })
  return { a1: rot(0, hexHeight), a2: rot(0.75 * hexWidth, 0.5 * hexHeight) }
}

export function hexOutlineSamples(hexWidth, hexHeight, perEdge = 4) {
  const s = hexWidth / 2
  const hh = hexHeight / 2
  const corners = [
    [s, 0], [s / 2, hh], [-s / 2, hh], [-s, 0], [-s / 2, -hh], [s / 2, -hh],
  ]
  const pts = []
  for (let e = 0; e < 6; e++) {
    const [ax, ay] = corners[e]
    const [bx, by] = corners[(e + 1) % 6]
    for (let k = 0; k < perEdge; k++) {
      const t = (k + 0.5) / perEdge
      pts.push([ax + (bx - ax) * t, ay + (by - ay) * t])
    }
  }
  return pts
}

function bilinear(f, width, x, y) {
  const x0 = Math.floor(x)
  const y0 = Math.floor(y)
  const fx = x - x0
  const fy = y - y0
  const i = y0 * width + x0
  return (
    f[i] * (1 - fx) * (1 - fy) +
    f[i + 1] * fx * (1 - fy) +
    f[i + width] * (1 - fx) * fy +
    f[i + width + 1] * fx * fy
  )
}

function makeAnchorScorer(field, width, height, params) {
  const { a1, a2 } = latticeFromParams(params)
  const rad = (params.rotation * Math.PI) / 180
  const cos = Math.cos(rad)
  const sin = Math.sin(rad)
  const pts = hexOutlineSamples(params.hexWidth, params.hexHeight).map(([x, y]) => [
    x * cos - y * sin,
    x * sin + y * cos,
  ])
  const cells = []
  for (let i = -2; i <= 2; i++) {
    for (let j = -2; j <= 2; j++) {
      cells.push([i * a2.x + j * a1.x, i * a2.y + j * a1.y])
    }
  }
  return (tx, ty) => {
    let acc = 0
    let cnt = 0
    for (const [cx, cy] of cells) {
      for (const [px, py] of pts) {
        const x = tx + cx + px
        const y = ty + cy + py
        if (x < 1 || y < 1 || x >= width - 2 || y >= height - 2) continue
        acc += bilinear(field, width, x, y)
        cnt++
      }
    }
    return cnt ? acc / cnt : 0
  }
}

function gridDescend(score, x0, y0, step0, minStep, maxDist) {
  let bx = x0
  let by = y0
  let bv = score(x0, y0)
  let step = step0
  const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [1, -1], [-1, 1], [-1, -1]]
  while (step >= minStep) {
    let moved = false
    for (const [dx, dy] of dirs) {
      const nx = bx + dx * step
      const ny = by + dy * step
      if (Math.hypot(nx - x0, ny - y0) > maxDist) continue
      const v = score(nx, ny)
      if (v > bv) {
        bv = v
        bx = nx
        by = ny
        moved = true
      }
    }
    if (!moved) step /= 2
  }
  return { x: bx, y: by, v: bv }
}

export function findGridPhase(field, width, height, params) {
  const { a1, a2 } = latticeFromParams(params)
  const score = makeAnchorScorer(field, width, height, params)
  const cell = Math.max(0.75 * params.hexWidth, params.hexHeight)
  const steps = clamp(Math.ceil(cell / 2), 12, 48)
  const t0x = width / 2
  const t0y = height / 2
  let best = null
  let sum = 0
  let sumSq = 0
  for (let iu = 0; iu < steps; iu++) {
    for (let iv = 0; iv < steps; iv++) {
      const tx = t0x + (iu / steps) * a2.x + (iv / steps) * a1.x
      const ty = t0y + (iu / steps) * a2.y + (iv / steps) * a1.y
      const v = score(tx, ty)
      sum += v
      sumSq += v * v
      if (!best || v > best.v) best = { x: tx, y: ty, v }
    }
  }
  const total = steps * steps
  const mean = sum / total
  const std = Math.sqrt(Math.max(0, sumSq / total - mean * mean))
  if (!best || std === 0) return null
  const contrast = (best.v - mean) / std
  if (contrast < PHASE_MIN_CONTRAST) return null
  const refined = gridDescend(score, best.x, best.y, cell / steps, 0.02, cell)
  return { x: refined.x, y: refined.y, contrast }
}

export function reduceAnchor(t, a1, a2) {
  const det = a2.x * a1.y - a1.x * a2.y
  const u = (t.x * a1.y - a1.x * t.y) / det
  const v = (a2.x * t.y - t.x * a2.y) / det
  const fu = u - Math.floor(u)
  const fv = v - Math.floor(v)
  return { x: fu * a2.x + fv * a1.x, y: fu * a2.y + fv * a1.y }
}

export function liftAnchorNear(anchor, a1, a2, target) {
  const det = a2.x * a1.y - a1.x * a2.y
  const dx = target.x - anchor.x
  const dy = target.y - anchor.y
  const u = Math.round((dx * a1.y - a1.x * dy) / det)
  const v = Math.round((a2.x * dy - dx * a2.y) / det)
  return { x: anchor.x + u * a2.x + v * a1.x, y: anchor.y + u * a2.y + v * a1.y }
}

export function refineAnchorOnField(gray, width, height, params, start, maxDist) {
  const grad = boxBlur3(gradientMagnitude(gray, width, height), width, height)
  const score = makeAnchorScorer(grad, width, height, params)
  return gridDescend(score, start.x, start.y, Math.max(1, maxDist / 2), 0.02, maxDist)
}

export function detectHexGrid(gray, width, height) {
  const grad = gradientMagnitude(gray, width, height)
  const acr = autocorrelate(grad, width, height)
  if (!acr) return null
  const lattice = detectLattice(acr.ac, acr.n)
  if (!lattice) return null
  const phase = findGridPhase(boxBlur3(grad, width, height), width, height, lattice)
  if (!phase) return null
  const { a1, a2 } = latticeFromParams(lattice)
  const anchor = reduceAnchor(phase, a1, a2)
  return {
    hexWidth: lattice.hexWidth,
    hexHeight: lattice.hexHeight,
    rotation: lattice.rotation,
    anchorX: anchor.x,
    anchorY: anchor.y,
    confidence: phase.contrast,
  }
}

function rotateAbout(p, deg, cx, cy) {
  const rad = (deg * Math.PI) / 180
  const cos = Math.cos(rad)
  const sin = Math.sin(rad)
  const x = p.x - cx
  const y = p.y - cy
  return { x: cx + x * cos - y * sin, y: cy + x * sin + y * cos }
}

function round2(v) {
  return Math.round(v * 100) / 100
}

export function alignmentPatchFromDetection(det, ctx) {
  const scale = ctx.imageScale ?? 1
  const imageRotation = ctx.imageRotation ?? 0
  const hexWidth = round2(det.hexWidth * scale)
  const hexHeight = round2(det.hexHeight * scale)
  const gridRotation = Math.round(det.rotation + imageRotation)
  const cx = (ctx.naturalWidth * scale) / 2
  const cy = (ctx.naturalHeight * scale) / 2
  const rotated = rotateAbout({ x: det.anchorX * scale, y: det.anchorY * scale }, imageRotation, cx, cy)
  const anchorWorld = {
    x: rotated.x + (ctx.imageOffsetX ?? 0),
    y: rotated.y + (ctx.imageOffsetY ?? 0),
  }
  let best = null
  for (let q = -2; q <= 2; q++) {
    for (let r = -2; r <= 2; r++) {
      const p = hexToPixel(q, r, hexWidth / 2, hexHeight)
      const rp = rotateAbout(p, gridRotation, cx, cy)
      const gx = anchorWorld.x - rp.x
      const gy = anchorWorld.y - rp.y
      const dist = gx * gx + gy * gy
      if (!best || dist < best.dist) best = { gx, gy, dist }
    }
  }
  return {
    mapHexWidth: hexWidth,
    mapHexHeight: hexHeight,
    mapGridRotation: gridRotation,
    mapGridOffsetX: Math.round(best.gx),
    mapGridOffsetY: Math.round(best.gy),
  }
}
